# -*- mode: sh; fill-column: 72; coding: utf-8 -*-

# ----------------------------------------------------------------------
# environment variables and stuff
# ----------------------------------------------------------------------
if [ -f "${HOME}/.profile" ]; then
    source "${HOME}/.profile"
fi

# ----------------------------------------------------------------------
# aliases
# ----------------------------------------------------------------------
if [ -f "${HOME}/.bash_aliases" ]; then
    source "${HOME}/.bash_aliases"
fi

# ----------------------------------------------------------------------
# auto completion
# ----------------------------------------------------------------------
if [ -f "${HOME}/.bash_completion" ]; then
    source "${HOME}/.bash_completion"
fi

# ----------------------------------------------------------------------
# terminal config stuff
# ----------------------------------------------------------------------

# Bash prompt
if [ -f "${HOME}/.bash_prompt" ]; then
    source "${HOME}/.bash_prompt"
fi

# For color output with `ls`
# See http://apple.stackexchange.com/q/33677/85567
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# ----------------------------------------------------------------------
# Python
# ----------------------------------------------------------------------
source /usr/local/bin/virtualenvwrapper.sh

# For overriding the requirement of being in pip virtualenv
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
gpip3(){
    PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}

