# -*- mode: sh; fill-column: 72 -*-

# -----------------------------------------------------------------------
# environment variables and stuff
# -----------------------------------------------------------------------
if [ -f "${HOME}/.profile" ]; then
    source "${HOME}/.profile"
fi

# -----------------------------------------------------------------------
# aliases
# -----------------------------------------------------------------------
if [ -f "${HOME}/.bash_aliases" ]; then
    source "${HOME}/.bash_aliases"
fi

# -----------------------------------------------------------------------
# auto completion
# -----------------------------------------------------------------------
if [ -f "${HOME}/.bash_completion" ]; then
    source "${HOME}/.bash_completion"
fi

# -----------------------------------------------------------------------
# terminal config stuff
# -----------------------------------------------------------------------

# For adding git info to prompt
function parse_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1) /'
}
PS1="\[\e[92m\]\$(parse_git_branch)\[\e[97m\]\u\[\e[92m\]@\[\e[95m\]\h\[\e[92m\]:\[\e[95m\]\W \$ \[\e[m\]"
export PS1

# For color output with `ls`
# See http://apple.stackexchange.com/q/33677/85567
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# -----------------------------------------------------------------------
# Python
# -----------------------------------------------------------------------
source /usr/local/bin/virtualenvwrapper.sh

# For overriding the requirement of being in pip virtualenv
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
gpip3(){
    PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}

